<?php

namespace App\Repository;

/**
 * ActiveApplicationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ActiveApplicationRepository extends \Doctrine\ORM\EntityRepository
{
}
