<?php

namespace App\Repository;

/**
 * ApiReaderRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ApiReaderRepository extends \Doctrine\ORM\EntityRepository
{
}
