<?php

namespace App\Repository;

/**
 * ApiReaderRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ApiReaderRepository extends BaseRepository
{
    /**
     * Returns the user's own data for this repository.
     *
     * @param int $userId
     *
     * @return array
     */
    public function my($userId = -1)
    {
        return $this->findBy(
            [
                'owner' => $userId
            ]
        );
    }
}
