<?php

namespace App\Repository;

/**
 * ComputerUsageSnapshotRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ComputerUsageSnapshotRepository extends \Doctrine\ORM\EntityRepository
{
}
