<?php

namespace App\Repository;

/**
 * InspectionDataSummaryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InspectionDataSummaryRepository extends \Doctrine\ORM\EntityRepository
{
}
