<?php

namespace App\Repository;

/**
 * KeyComboRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class KeyComboRepository extends \Doctrine\ORM\EntityRepository
{
}
