<?php

namespace App\Repository;

/**
 * KeyStrokeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class KeyStrokeRepository extends \Doctrine\ORM\EntityRepository
{
}
