<?php

namespace App\Repository;

/**
 * MousePositionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MousePositionRepository extends \Doctrine\ORM\EntityRepository
{
}
