<?php

namespace App\Repository;

/**
 * MousePathRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MousePathRepository extends \Doctrine\ORM\EntityRepository
{
}
