<?php

namespace App\Repository;

/**
 * MouseClickRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MouseClickRepository extends \Doctrine\ORM\EntityRepository
{
}
