<?php

namespace App\Repository;

/**
 * PermissionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PermissionRepository extends BaseRepository
{
    /**
     * Checks the user rights for this module.
     *
     * @return PermissionRepository
     */
    public function scopeRights()
    {
        // TODO: Implement scopeRights() method.
        return $this;
    }
}
