<?php

namespace App\Repository;

/**
 * SearchSettingRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SearchSettingRepository extends BaseRepository
{
    /**
     * Returns own search settings.
     */
    public function my()
    {
        // TODO: Implement my() method.
    }
}
