<?php

namespace App\Repository;

/**
 * SettingsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SettingsRepository extends BaseRepository
{
    /**
     * Returns the user's own data for this repository.
     *
     * @return SettingsRepository
     */
    public function my()
    {
        // TODO: Implement my() method.

        return $this;
    }
}
