language: php

sudo: false

cache:
  directories:
    - $HOME/.composer/cache/files

git:
  depth: 1

services:
  - mysql

php:
  - 7.0

env:
  - SYMFONY_ENV=test

matrix:
  fast_finish: true

install:
  - composer install
  - bash init.sh -p=hilavitkutin
  - php bin/console doctrine:database:create
  - php bin/console doctrine:schema:create
  - php bin/console doctrine:fixtures:load --append

before_script:
  - php bin/console --version