# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
    annotation_driver:
        class: App\Annotation\AnnotationDriver
        tags: [{name: kernel.event_listener, event: kernel.controller, method: onKernelController}]
        arguments: ['@annotation_reader', '@service_container', '@request_stack']
    my.listener:
        class: App\Listener\PostUpdate
        tags:
            - { name: doctrine.event_listener, event: postUpdate }